worker: tornado


handlers:
- url: /static
  static_dir: static
- url: /build
  static_dir: build 
- url: /css
  static_dir: css 
- url: /js
  static_dir: js 
- url: /favicon\.ico
  static_dir: /static/favicon\.ico 
